# Generated by Django 3.1.2 on 2022-10-31 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_Commande']},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_Commande',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
