# Generated by Django 3.1.2 on 2022-10-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221031_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
