# Generated by Django 3.1.2 on 2022-10-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
    ]
