# Generated by Django 3.1.2 on 2022-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_commande_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
