# Generated by Django 3.1.2 on 2022-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221031_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='item_list',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='Item',
            field=models.CharField(max_length=1000),
        ),
    ]
