# Generated by Django 3.1.2 on 2022-10-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221031_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='item_list',
        ),
    ]
