# Generated by Django 3.1.2 on 2022-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221031_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=400),
        ),
    ]
