# Generated by Django 3.1.2 on 2022-10-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221031_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
    ]
