# Generated by Django 3.1.2 on 2022-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_commande_liste'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='totale',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
