# Generated by Django 3.1.2 on 2022-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_commande_totale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='liste',
            field=models.CharField(max_length=500),
        ),
    ]
