# Generated by Django 3.1.2 on 2022-11-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20221101_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='liste',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='totale',
            new_name='total',
        ),
    ]
