# Generated by Django 3.1.2 on 2022-11-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221102_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
    ]
